---
- hosts: master
  tasks:
  - name: install flannel
    shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/bc79dd1505b0c8681ece4de4c0d86c5cd2643275/Documentation/kube-flannel.yml
    args:
      executable: /bin/bash

  - name: kubectl get nodes
    shell: kubectl get nodes
    args:
      executable: /bin/bash